### ISSUE TITLE
Window Formatting

### ISSUE THREAD

**Issue by pelovett** [lovett2/TooLongDidntRead#10]
Make window wider. Create window when no text is selected to prompt user to select text. Automatically summarize when icon clicked (if time).

**Comment by lovett2** [comment]
I think we can close this, right? We decided that showing what was going to be summarized was helpful, the window has been widened, and the user gets relevant messages like when an issue occurs or if the user needs to wait while we grab the input text.

**Comment by cathmwebster** [comment]
I think it can be closed

**Comment by cathmwebster** [comment]
I will close, since this is done.
