### ISSUE TITLE
Design Documentation 

### ISSUE THREAD

**Issue by pelovett** [lovett2/TooLongDidntRead#11]
Create documentation that allows for developers to extend the extension. Should clarify what files do what for the functionality of the code.

**Comment by cathmwebster** [comment]
Wrote all of the design doc per grading rubric on course website. Possibly adding a diagram might help

**Comment by lovett2** [comment]
For some reason, the Milestones link seems to be broken, but I can't see why...

**Comment by cathmwebster** [comment]
Fixed it!

**Comment by cathmwebster** [comment]
add ScapeAPI info

**Comment by cathmwebster** [comment]
Add new milestone-- no more highlighting, text is self grabbing

**Comment by cathmwebster** [comment]
Added section for "known issues" which will have the bugs that our app has

**Comment by cathmwebster** [comment]
merged to master
