### ISSUE TITLE
Title feature on Summarizer

### ISSUE THREAD

**Issue by cathmwebster** [lovett2/TooLongDidntRead#14]
The title feature on summarizer isn't really doing anything right now, since the title isn't always going to be highlighted. Possibly remove it... or just ignore it

**Comment by lovett2** [comment]
Are you talking about in the button.js file? Where it assigns title to be "TL;DR" ? I'm confused - did someone already remove the title component and replace it with TL;DR?

**Comment by cathmwebster** [comment]
Originally with the highlighting feature, we couldn't really tell what the title was. I think with the API we are using to get the content text, we can just search for the title and use it

**Comment by lovett2** [comment]
What do people think about using JSON as our output for the scraper? Then it separates out the title.

**Comment by cathmwebster** [comment]
I feel like the title is unnecessary because the user is on the page and they can see the title...

**Comment by lovett2** [comment]
Closing this issue as the group majority is voting not to include the title.
