### ISSUE TITLE
Create README.md

### ISSUE THREAD

**Issue by cathmwebster** [lovett2/TooLongDidntRead#5]
"The README file of your repository should be brief but should give me everything I need to determine what your project is, who its authors (you) are, and a basic outline of what the build process and the resulting product are. It may contain links to additional material."

-Authors
-Summary of our product
-System requirements
-Design documentation
-Build process (manual step-by-step instruction)

**Comment by lovett2** [comment]
I've got most of this - I'll add system requirements, then probably ask for input from everyone.

**Comment by cathmwebster** [comment]
I think we need a "technologies used" section

**Comment by lovett2** [comment]
I'll get on it!
